routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/* ============================ MARKETING ============================= */
use App\Http\Controllers\Marketing\DashboardController as DashboardMarketing;
use App\Http\Controllers\Marketing\CustomerController as MarketingCustomer;

/* ============================ STAFF TEKNIS ============================= */
use App\Http\Controllers\StaffTeknis\DashboardController as DashboardStaffTeknis;
use App\Http\Controllers\StaffTeknis\DeviceController;
use App\Http\Controllers\StaffTeknis\PacketController;
use App\Http\Controllers\StaffTeknis\SubscribeCandidateController as SubscribeStaffTeknis;

/* ============================ FINANCE ============================= */
use App\Http\Controllers\Finance\DashboardController as DashboardFinance;

/* ============================ CUSTOMER LOGIN ============================= */
use App\Http\Controllers\Customer\DashboardController as DashboardCustomer;
use App\Http\Controllers\Customer\ProfileController as ProfileCustomer;
use App\Http\Controllers\Customer\SubscribeController as SubscribeCustomer;

/* ============================ CUSTOMER ============================= */
use App\Http\Controllers\HomeController;

/* ============================ OAUTH ============================= */
use App\Http\Controllers\Auth\GithubController;
use App\Http\Controllers\Auth\FacebookController;
use App\Http\Controllers\Auth\GoogleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
\URL::forceScheme('https');

Auth::routes(['verify' => true]);

// Verifikasi email
Route::middleware('auth')->get('/email/verify', function () {
    return view('auth.verify');
})->name('verification.notice');

// Reset password
Route::get('/forgot-password', function () {
    return view('auth.passwords.email');
})->middleware('guest')->name('password.request');

/* ============================ OAUTH GITHUB ============================= */
Route::get('oauth/github/redirect', [GithubController::class, 'redirect'])->name('oauth.github.redirect');
Route::get('oauth/github/callback', [GithubController::class, 'callback'])->name('oauth.github.callback');

/* ============================ OAUTH FACEBOOK ============================= */
Route::get('oauth/fb/redirect', [FacebookController::class, 'redirect'])->name('oauth.fb.redirect');
Route::get('oauth/fb/callback', [FacebookController::class, 'callback'])->name('oauth.fb.callback');
Route::get('oauth/fb/privacy', [FacebookController::class, 'privacy'])->name('oauth.fb.privacy');
Route::get('oauth/fb/delete-data', [FacebookController::class, 'deleteData'])->name('oauth.fb.delete-data');

/* ============================ OAUTH GOOGLE ============================= */
Route::get('oauth/google/redirect', [GoogleController::class, 'redirect'])->name('oauth.google.redirect');
Route::get('oauth/google/callback', [GoogleController::class, 'callback'])->name('oauth.google.callback');

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
	/* ============================ MARKETING ============================= */
	Route::group(['prefix' => 'marketing', 'middleware' => 'marketing'], function () {
		Route::get('/', [DashboardMarketing::class, 'index'])->name('dashboard.marketing');

		Route::group(['prefix' => 'customer'], function () {
			Route::get('/', [MarketingCustomer::class, 'index'])->name('marketing.customer');
			Route::get('/create', [MarketingCustomer::class, 'create'])->name('marketing.customer.create');
			Route::post('/store', [MarketingCustomer::class, 'store'])->name('marketing.customer.store');
			Route::get('/edit/{id}', [MarketingCustomer::class, 'edit'])->name('marketing.customer.edit');
			Route::put('/update/{id}', [MarketingCustomer::class, 'update'])->name('marketing.customer.update');
			Route::get('/show/{id}', [MarketingCustomer::class, 'show'])->name('marketing.customer.show');
		});
	});

	/* ============================ STAFF TEKNIS ============================= */
	Route::group(['prefix' => 'staff-teknis', 'middleware' => 'staff-teknis'], function () {
		Route::get('/', [DashboardStaffTeknis::class, 'index'])->name('dashboard.staff-teknis');

		Route::group(['prefix' => 'device'], function () {
			Route::get('/', [DeviceController::class, 'index'])->name('staff-teknis.device');
			Route::get('/create', [DeviceController::class, 'create'])->name('staff-teknis.device.create');
			Route::post('/', [DeviceController::class, 'store'])->name('staff-teknis.device.store');
			Route::get('/{id}', [DeviceController::class, 'edit'])->name('staff-teknis.device.edit');
			Route::put('/{id}', [DeviceController::class, 'update'])->name('staff-teknis.device.update');
			Route::delete('/{id}', [DeviceController::class, 'destroy'])->name('staff-teknis.device.destroy');
		});

		Route::group(['prefix' => 'packet'], function () {
			Route::get('/', [PacketController::class, 'index'])->name('staff-teknis.packet');
			Route::get('/create', [PacketController::class, 'create'])->name('staff-teknis.packet.create');
			Route::post('/', [PacketController::class, 'store'])->name('staff-teknis.packet.store');
			Route::get('/{id}', [PacketController::class, 'edit'])->name('staff-teknis.packet.edit');
			Route::put('/{id}', [PacketController::class, 'update'])->name('staff-teknis.packet.update');
			Route::delete('/{id}', [PacketController::class, 'destroy'])->name('staff-teknis.packet.destroy');
		});

		Route::group(['prefix' => 'subscibe-candidate'], function () {
			Route::get('/', [SubscribeStaffTeknis::class, 'index'])->name('staff-teknis.subscribe-candidate');
			Route::get('/{id}', [SubscribeStaffTeknis::class, 'show'])->name('staff-teknis.subscribe-candidate.show');
			Route::delete('/{id}', [SubscribeStaffTeknis::class, 'destroy'])->name('staff-teknis.subscribe-candidate.destroy');
		});
	});

	/* ============================ FINANCE ============================= */
	Route::group(['middleware' => 'finance'], function () {
		Route::get('/finance', [DashboardFinance::class, 'index'])->name('dashboard.finance');
	});

	/* ============================ CUSTOMER LOGIN ============================= */
	Route::group(['prefix' => 'customer', 'middleware' => 'customer'], function () {
		Route::get('/', [DashboardCustomer::class, 'index'])->name('dashboard.customer');

		Route::get('/profile', [ProfileCustomer::class, 'index'])->name('customer.profile');
		Route::put('/profile', [ProfileCustomer::class, 'update'])->name('customer.profile.update');

		Route::group(['middleware' => 'customer.complete'], function () {
			Route::get('/subscribe/{id}', [SubscribeCustomer::class, 'store'])->name('customer.subscribe.store');
		});
	});
});

/* ============================ CUSTOMER ============================= */
Route::get('/', [HomeController::class, 'index'])->name('landing-page');

app/Models/Subscribe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Subscribe extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [];

    public function customer()
    {
    	return $this->belongsTo(Customer::class);
    }

    public function packet()
    {
    	return $this->hasOne(Packet::class, 'id', 'packet_id');
    }

    public function schedules()
    {
    	return $this->hasMany(Schedule::class);
    }

    public function getDateDiffAttribute()
    {
    	return dateDiff($this->attributes['created_at']);
    }
}

app/Http/Controllers/StaffTeknis/SubscribeCandidateController.php
<?php

namespace App\Http\Controllers\StaffTeknis;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Subscribe;
use App\Models\Employee;
use App\Models\Device;
use App\Models\Schedule;

class SubscribeCandidateController extends Controller
{
	function __construct(Request $request)
	{
		$this->request = $request;
	}

	public function index()
	{
        try {
            $subscribes = Subscribe::with('customer', 'packet')
            			  ->where('status', env('SUB2'))
            			  ->get();

            return view('dashboard-staff-teknis.subscribe-candidate.index', compact('subscribes'));
        } catch (\Throwable $th) {
            writeLog($th->getMessage());
        }
	}

	public function show($id)
	{
        try {
            $subscribe = Subscribe::with('customer', 'packet')
            			 ->where('status', env('SUB2'))
            			 ->first();

            $allEmployee = Employee::whereHas('user', function ($query) {
            	$query->where('role', env('ROLE2'));
            })->get();

            $allDevice = Device::all();

            if (!$subscribe) {
            	return redirect()->back()->with('error', 'Data tidak ditemukan');
            }

            return view('dashboard-staff-teknis.subscribe-candidate.show', compact('subscribe'));
        } catch (\Throwable $th) {
            writeLog($th->getMessage());
        }
	}
}

resources/views/dashboard-staff-teknis/subscribe-candidate/index.blade.php
@extends('layouts.dashboard.app')

@section('title', 'Subscribe | HMN')

@section('main-content')
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0">Calon Pelanggan</h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item"><a href="{{ route('landing-page') }}"><i class="fas fa-home"></i></a></li>
              <li class="breadcrumb-item"><a href="{{ route('dashboard.staff-teknis') }}">Dashboard</a></li>
              <li class="breadcrumb-item active" aria-current="page">Calon Pelanggan</li>
            </ol>
          </nav>
        </div>
        {{-- <div class="col-lg-6 col-5 text-right">
          <a href="{{ route('staff-teknis.packet.create') }}" class="btn btn-sm btn-neutral"><i class="fas fa-plus"></i> Tambah</a>
        </div> --}}
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-xl-12 col-md-12 col-sm-12">
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover my-datatable">
              <thead>
                <th>No</th>
                <th>Nama</th>
                <th>Hp / Whatsapp</th>
                <th>Paket</th>
                <th>Tanggal</th>
                <th></th>
              </thead>
              <tbody>
                @foreach($subscribes as $subscribe)
                <tr>
                  <td>{{ $loop->iteration }}</td>
                  <td>{{ $subscribe->customer->name }}</td>
                  <td>{{ $subscribe->customer->phone }} / {{ $subscribe->customer->whatsapp }}</td>
                  <td>{{ $subscribe->packet->name }}</td>
                  <td>{{ $subscribe->date_diff }}</td>
                  <td>
                    <form action="{{ route('staff-teknis.subscribe-candidate.destroy', $subscribe->id) }}" method="post" id="form-{{ $subscribe->id }}">
                      @csrf
                      @method('DELETE')
                      <a href="{{ route('staff-teknis.subscribe-candidate.show', $subscribe->id) }}" class="btn btn-success btn-sm text-white">
                        <i class="fas fa-eye"></i>
                      </a>
                      <button type="button" class="btn btn-danger btn-sm text-white btn-hapus" data-id="{{ $subscribe->id }}">
                        <i class="fas fa-trash"></i>
                      </button>
                    </form>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  @include('layouts.dashboard.footer')
</div>
@endsection

@section('custom-js')
<script>
  $('.btn-hapus').on('click', function (e) {
    let id = e.target.dataset['id']

    Swal.fire({
      title: 'Peringatan',
      text: 'Yakin mau hapus data ini?',
      icon: 'warning',
      showCancelButton: true,
    }).then((data) => {
      if (data.isConfirmed) {
        $(`#form-${id}`).submit()
      }
    })
  })
</script>
@endsection

resources/views/dashboard-staff-teknis/subscribe-candidate/show.blade.php
@extends('layouts.dashboard.app')

@section('title', 'Subscribe | HMN')

@section('custom-css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
@endsection

@section('main-content')
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0">Detail Calon Pelanggan</h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item"><a href="{{ route('landing-page') }}"><i class="fas fa-home"></i></a></li>
              <li class="breadcrumb-item"><a href="{{ route('staff-teknis.subscribe-candidate') }}">Calon Pelanggan</a></li>
              <li class="breadcrumb-item active" aria-current="page">Detail</li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="{{ route('staff-teknis.subscribe-candidate') }}" class="btn btn-sm btn-neutral"><i class="fas fa-arrow-left"></i> Kembali</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-xl-6 col-md-6 col-sm-12">
      <div class="card">
        <div class="card-body">
          <div class="row mb-3">
            <div class="col-md-4 col-sm-4">Nama</div>
            <div class="col-md-8 col-sm-8">: {{ $subscribe->customer->name }}</div>
          </div>
          <div class="row mb-3">
            <div class="col-md-4 col-sm-4">No HP</div>
            <div class="col-md-8 col-sm-8">: {{ $subscribe->customer->phone }}</div>
          </div>
          <div class="row mb-3">
            <div class="col-md-4 col-sm-4">Whatsapp</div>
            <div class="col-md-8 col-sm-8">: {{ $subscribe->customer->whatsapp }}</div>
          </div>
          <div class="row mb-3">
            <div class="col-md-4 col-sm-4">Foto</div>
            <div class="col-md-8 col-sm-8">
              <a data-fancybox="gallery" href="{{ asset($subscribe->customer->photo) }}">
                <img class="img-thumbnail" src="{{ asset($subscribe->customer->photo) }}" alt="Foto" width="200">
              </a>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-4 col-sm-4">Foto KTP</div>
            <div class="col-md-8 col-sm-8">
              <a data-fancybox="gallery" href="{{ asset($subscribe->customer->id_card) }}">
                <img class="img-thumbnail" src="{{ asset($subscribe->customer->id_card) }}" alt="Foto KTP" width="200">
              </a>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-4 col-sm-4">Nama Paket</div>
            <div class="col-md-8 col-sm-8">: {{ $subscribe->packet->name }}</div>
          </div>
          <div class="row mb-3">
            <div class="col-md-4 col-sm-4">Harga</div>
            <div class="col-md-8 col-sm-8">: {{ $subscribe->packet->price }}</div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-6 col-md-6 col-sm-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-12 col-sm-12">
              <div style="width: 100%; height: 480px" id="map-container"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xl-12 col-md-12 col-sm-12">
      <div class="card">
        <div class="card-body">
          <form action="#" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            @if ($errors->any())
              <div class="alert alert-danger">
                <ul>
                  @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                  @endforeach
                </ul>
              </div>
            @endif
            <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="form-group">
                  <label class="form-control-label" for="input-name">Nama</label>
                  <input type="text" id="input-name" class="form-control" placeholder="Nama" value="{{ '' }}" name="name">
                </div>
              </div>
              <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="form-group">
                  <label class="form-control-label" for="input-price">Harga</label>
                  <input type="number" id="input-price" class="form-control" placeholder="Harga" value="{{ '' }}" name="price" min="1">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="form-group">
                  <label class="form-control-label">Deskripsi</label>
                  <textarea rows="4" class="form-control my-textarea" placeholder="Deskripsi" name="description">{{ '' }}</textarea>
                </div>
              </div>
            </div>
            <div class="row mt-3">
              <div class="col-md-12 col-sm-12">
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a href="{{ route('staff-teknis.subscribe-candidate') }}" class="btn btn-secondary">Batal</a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  @include('layouts.dashboard.footer')
</div>
@endsection

@section('custom-js')
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<script src="https://js.api.here.com/v3/3.1/mapsjs-core.js" type="text/javascript" charset="utf-8"></script>
<script src="https://js.api.here.com/v3/3.1/mapsjs-service.js" type="text/javascript" charset="utf-8"></script>
<script src="https://js.api.here.com/v3/3.1/mapsjs-ui.js" type="text/javascript" charset="utf-8"></script>
<script src="https://js.api.here.com/v3/3.1/mapsjs-mapevents.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" type="text/css" href="https://js.api.here.com/v3/3.1/mapsjs-ui.css" />
<script>
  $(document).ready(function () {
    navigator.geolocation.getCurrentPosition(function(position) {
      let lat  = '{{ $subscribe->customer->latitude }}'
      let long = '{{ $subscribe->customer->longitude }}'

      function addDraggableMarker(peta, behavior){
        // create marker
        let marker = new H.map.Marker({
          lat: lat,
          lng: long
        },
        {
          // mark the object as volatile for the smooth dragging
          volatility: true
        })

        // Add the marker to the map and center the map at the location of the marker:
        peta.addObject(marker)

        // Ensure that the marker can receive drag events
        marker.draggable = true
        peta.addObject(marker)

        // disable the default draggability of the underlying map
        // and calculate the offset between mouse and target's position
        // when starting to drag a marker object:
        peta.addEventListener('dragstart', function(ev) {
          let target = ev.target
          let pointer = ev.currentPointer

          if (target instanceof H.map.Marker) {
            let targetPosition = peta.geoToScreen(target.getGeometry())
            target['offset'] = new H.math.Point(pointer.viewportX - targetPosition.x, pointer.viewportY - targetPosition.y)
            behavior.disable()
          }
        }, false)

        // re-enable the default draggability of the underlying map
        // when dragging has completed
        peta.addEventListener('dragend', function(ev) {
          let target = ev.target
          // document.getElementById('input-longitude').value = target.b.lng
          // document.getElementById('input-latitude').value = target.b.lat

          if (target instanceof H.map.Marker) {
            behavior.enable()
          }
        }, false)

        // Listen to the drag event and move the position of the marker
        // as necessary
        peta.addEventListener('drag', function(ev) {
          let target = ev.target
          let pointer = ev.currentPointer
          if (target instanceof H.map.Marker) {
            target.setGeometry(peta.screenToGeo(pointer.viewportX - target['offset'].x, pointer.viewportY - target['offset'].y))
          }
        }, false)
      }

      let platform = new H.service.Platform({
        'apikey': '{{ env('HEREMAPS_API_KEY') }}'
      })

      // Obtain the default map types from the platform object:
      let defaultLayers = platform.createDefaultLayers()

      // Instantiate (and display) a map object:
      let peta = new H.Map(
        document.getElementById('map-container'),
        defaultLayers.vector.normal.map,
        {
          zoom: 15,
          center: {
            lat: lat,
            lng: long
          }
        }
      )

      // add a resize listener to make sure that the map occupies the whole container
      window.addEventListener('resize', () => peta.getViewPort().resize())

      // Add map events functionality to the map
      let mapEvents = new H.mapevents.MapEvents(peta)

      // Add behavior to the map: panning, zooming, dragging.
      let behavior = new H.mapevents.Behavior(mapEvents)

      // map ui
      let ui = H.ui.UI.createDefault(peta, defaultLayers)

      // Add the click event listener
      addDraggableMarker(peta, behavior)
    })
  })
</script>
@endsection